### ISSUE TITLE
Cambios weird-ass cats - Marta & Jon Ander

### ISSUE THREAD

**Issue by jonanderp1** [miguelsimon/ejercicios#3]
**Tareas @arraezmarta  (MA)**
Cambios html:
- [x] Cambios en la estructura del index.html
- [x] Añadir logo
- [x] Añadir enlaces a otras páginas (menú)
- [x] Generar otras páginas html
- [x] Añadir pie de foto
- [x] Hacer PR para que JA pueda seguir con el CSS a partir de los cambios de MA
- [x] Una vez que Miji acepte el PR de JA, MA deja su repo local actualizado con lo últimos cambios
- [x] Unificar logo

**Tareas @jonanderp1  (JA)**
Cambios css:
- [x] Actualizar repo local con cambios de MA
- [x] Cambiar colores y estilos de texto.
- [x] Aplicar estilo al menú
- [x] Cambios en la estructura para que quede centrado
- [x] Aplicar hover a las fotos para que se desplacen hacía arriba y aparezca box-shadow
- [x] Hacer PR con los cambios de MA y JA
- [x] Hacer que el logo sea un enlace a la home

**Tareas @valentinboyanov  (VA)**
Solucionar bugs:
- [x] Navegación

**Bonus track**
Cambios extra:
- [x] @arraezmarta  --> Igual las imgs de tamaño a 630px de width
- [x] @valentinboyanov --> Cambiar la url de los gatos "index.html" --> "gatos.html", poner la url correta en el menu
- [x] @jonanderp1 --> Crear un index con imgs de cada animalito y enlaces a sus páginas.

**Comment by miguelsimon** [comment]
Muy buena pinta 👍 

 una sugerencia: ante la duda, mejor hacer varios PRs con cambios sencillos antes que uno grande con cambios complejos, así rompemos mano con el workflow 🙂 

Otra sugerencia: si se menciona a los participantes eg. @jonanderp1 y @arraezmarta se autosuscriben al issue.

**Comment by jonanderp1** [comment]
Gracias por la sugerencia @miguelsimon :)
Aunque ya habíamos comenzado cuando lo hemos leído y te hemos dejado un PR con varias cositas ;)

**Comment by jonanderp1** [comment]
@valentinboyanov puedes poner tu también la url correcta de los gatos en el menú del resto de htmls? 

cc/ @arraezmarta

**Comment by miguelsimon** [comment]
Cierro esto que ha cumplido su función 🎉
