### ISSUE TITLE
Ejercicio 6

### ISSUE THREAD

**Issue by juanaperaita** [miguelsimon/ejercicios#38]
**Parte 1**

![ej_6_parte_1](https://user-images.githubusercontent.com/126180492/230170355-a63ce718-41f0-489d-90c3-4808f76bf382.png)

**Comment by juanaperaita** [comment]
El fenómeno que ha encontrado la Dra. Simpson se llama la [Paradoja de Simpson](https://es.wikipedia.org/wiki/Paradoja_de_Simpson) y indica que una tendencia observada en un subconjunto de datos concreto puede cambiar si se observa el conjunto de datos general. Teniendo en cuenta esto, es posible que en la franja de edad de 50-52 años, el ejercicio excesivo pueda ser perjudicial en cuanto al thanatol, pero habría que mirar cada caso concreto para ver qué es mejor recomendar según la edad de los pacientes.

**Comment by juanaperaita** [comment]
Hay 2 variables: Edad y deporte. Respecto a la edad, como no sé cuál debería ser el tramo de edad, empezaría cogiendo tramos de edad anuales, siempre y cuando la muestra de cada año de edad sea suficientemente representativa para poder hacer el análisis. Si un año no tiene datos suficientes, lo juntaría con otro año para hacer un tramo bienal o lo despreciaría. 

Respecto al deporte, habría que hacer una definición de 3 grados de deporte, que habría que definir de una forma que homogeneice las respuestas. 

Si un paciente viene a la consulta, vería la incidencia según su edad (hemos quedado que era un año) y la tabla de deporte le recomendaría una cosa u otra. Si hacemos las tablas de un año y vemos que no cambian demasiado igual podríamos incluso pasar a tramos de 5 en 5 años.

**Comment by miguelsimon** [comment]
Cierro esto y acabamos de comentarlo offline en la siguiente reunión.
